version: '3.8'

services:
  bot:
    build:
      context: .
    container_name: diet_ai_bot
    restart: always
    stop_signal: SIGINT
    # Якщо головний файл bot.py, залишаємо так
    command: python bot.py
    env_file:
      - ".env"
    volumes:
      # Зберігаємо тільки базу даних, щоб при оновленні коду дані не зникали
      - ./tgbot/models:/usr/src/app/tgbot/models
    # Порти зазвичай не потрібні для Telegram ботів на long polling,
    # але якщо використовуєш webhooks — залиш
    ports:
      - "80:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: tg_bot_net